#!/usr/bin/env bash
# Compile the map viewer TypeScript sources (viewer/src) into the browser ES
# modules served by the static page (viewer/js):
#
#   js/app.js js/pack.js js/coerce.js js/map2d.js js/globe.js
#
# esbuild transforms each module in place (no --bundle): relative specifiers
# ("./map2d.js", the dynamic "./globe.js") survive verbatim, and the bare
# "three"/"three/addons/*" imports in globe.ts stay for the browser to resolve
# through index.html's importmap. That keeps the lazy first-use CDN fetch of
# three.js intact instead of vendoring it into the build.
#
# esbuild runs through bunx pinned by ESBUILD_VERSION (single source of truth:
# scripts/toolchain-versions.env, shared with build-webmod.sh). Outputs are
# generated artifacts (gitignored); regenerate after editing sources:
# make viewer-build.
#
# Override locally: ESBUILD_VERSION=0.28.2 bash scripts/build-viewer.sh

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "$root/scripts/toolchain-versions.env"
src_dir="$root/viewer/src"
out_dir="$root/viewer/js"

mkdir -p "$out_dir"

bunx "esbuild@$ESBUILD_VERSION" \
  "$src_dir/app.ts" \
  "$src_dir/pack.ts" \
  "$src_dir/coerce.ts" \
  "$src_dir/map2d.ts" \
  "$src_dir/globe.ts" \
  --outdir="$out_dir" \
  --format=esm \
  --target=es2022 \
  --log-level=warning \
  --banner:js='// Generated by scripts/build-viewer.sh from viewer/src; do not edit.'

for module in app pack coerce map2d globe; do
  if [ ! -s "$out_dir/$module.js" ]; then
    echo "realearth: build-viewer: missing or empty output $out_dir/$module.js" >&2
    exit 1
  fi
done

echo "realearth: viewer modules -> $out_dir/{app,pack,coerce,map2d,globe}.js"
