#!/usr/bin/env bash
# Compile the map viewer TypeScript sources (viewer/src) into the browser ES
# modules served by the static page (viewer/js):
#
#   js/app.js js/pack.js js/coerce.js js/map2d.js js/lonWrap.js js/globe.js
#
# esbuild transforms each module in place (no --bundle): relative specifiers
# ("./map2d.js", "./lonWrap.js", the dynamic "./globe.js") survive verbatim, and
# the bare "three"/"three/addons/*" imports in globe.ts stay for the browser to
# resolve through index.html's importmap. That keeps the lazy first-use CDN
# fetch of three.js intact instead of vendoring it into the build.
#
# esbuild is pinned by ESBUILD_VERSION (single source of truth:
# scripts/toolchain-versions.env) and installed from the committed lockfile by
# install-js-toolchain.sh, so the bundler binary itself is hash-verified
# instead of resolved from the registry on every run. Outputs are generated
# artifacts (gitignored); regenerate after editing sources:
# make viewer-build.
#
# Override locally: ESBUILD_VERSION=0.28.2 bash scripts/build-viewer.sh

set -euo pipefail

usage() {
  # Header comment with the leading '# ' stripped; a fixed line range would
  # shift whenever a note is added above it.
  awk 'NR == 1 { next } /^#/ { sub(/^# ?/, ""); print; next } { exit }' "$0"
}

case "${1:-}" in
  -h | --help)
    usage
    exit 0
    ;;
esac

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "$root/scripts/toolchain-versions.env"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/realearth/js-toolchain"
src_dir="$root/viewer/src"
out_dir="$root/viewer/js"

bash "$root/scripts/install-js-toolchain.sh" "$cache_dir" >/dev/null

mkdir -p "$out_dir"

"$cache_dir/node_modules/.bin/esbuild" \
  "$src_dir/app.ts" \
  "$src_dir/pack.ts" \
  "$src_dir/coerce.ts" \
  "$src_dir/map2d.ts" \
  "$src_dir/lonWrap.ts" \
  "$src_dir/globe.ts" \
  "$src_dir/rte.ts" \
  "$src_dir/rteLayer.ts" \
  --outdir="$out_dir" \
  --format=esm \
  --target=es2022 \
  --log-level=warning \
  --banner:js='// Generated by scripts/build-viewer.sh from viewer/src; do not edit.'

for module in app pack coerce map2d lonWrap globe rte rteLayer; do
  if [ ! -s "$out_dir/$module.js" ]; then
    echo "realearth: build-viewer: missing or empty output $out_dir/$module.js" >&2
    exit 1
  fi
done

echo "realearth: viewer modules -> $out_dir/{app,pack,coerce,map2d,lonWrap,globe,rte,rteLayer}.js"
